# Run `conda-env create -f install_gds_stack.yml`
name: gds
channels:
  - conda-forge
dependencies:
  - bokeh
  - cartopy
  - clusterpy
  - dask
  - geopandas
  - ipython
  - ipywidgets
  - jupyter
  - mplleaflet
  - networkx
  - palettable
  - pip
  - python=2.7
  - qgrid
  - rasterio
  - scikit-learn
  - seaborn
  - statsmodels
  - xlrd
  - xlsxwriter

